Seu_Nome = input("Digite seu nome: ")
Seu_CPF =input("Digite o seu CPF: ")
Seu_Endereço = input("Digite o seu endereço: ")
Seu_Email = input("Digite o seu email: ")
Numero_de_telefone = input("Digite o seu numero de telefone: ")
Sua_Nacionalidade = input("Digite sua nacionalidade: ")
Seu_Grau_de_instrução = input("Digite seu grau de instrucao:")
print()
print("Confira as informações abaixo")
print()
print("Seu nome :",Seu_Nome)
print("Seu CPF: ",Seu_CPF )
print("Seu endereço:", Seu_Endereço)
print("Seu email: ",Seu_Email)
print("Numero de telefone: ",Numero_de_telefone )
print("Sua nacionalidade: ",Sua_Nacionalidade)
print("Seu grau de instrução: ",Seu_Grau_de_instrução)
